"use client";
import Link from "next/link";
import { Compass, Database, Lightbulb } from "lucide-react";
import { useEffect, useState } from "react";
import { useWorkspaceIdentity } from "@/features/workspace/hooks/use-workspace-identity";
import { records, workspaceRequest } from "./client";
import type { OpportunitySummary, ResearchRunSummary, SourceSummary } from "./types";
import styles from "./workspace-pages.module.css";

function State({loading,error,empty,icon}:{loading:boolean;error:string|null;empty:string;icon:"runs"|"ideas"|"sources"}){const Icon=icon==="runs"?Compass:icon==="ideas"?Lightbulb:Database;if(loading)return <div className={styles.loading} aria-label="Loading"><span/><span/><span/></div>;if(error)return <p className={styles.error} role="alert">{error}</p>;return <div className={styles.empty}><Icon/><h2>Nothing here yet</h2><p>{empty}</p></div>}
function useCollection<T>(path:string,key:string){const identity=useWorkspaceIdentity();const [items,setItems]=useState<T[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);useEffect(()=>{if(identity.loading)return;if(!identity.context){queueMicrotask(()=>setLoading(false));return;}const query=new URLSearchParams({projectId:identity.context.projectId});void workspaceRequest<unknown>(identity.context.accessToken,`${path}?${query}`).then(payload=>setItems(records<T>(payload,key))).catch(cause=>setError(cause instanceof Error?cause.message:"Could not load this workspace." )).finally(()=>setLoading(false));},[identity.loading,identity.context,path,key]);return{identity,items,setItems,loading,error};}
export function ResearchRunsPage(){const {items,loading,error}=useCollection<ResearchRunSummary>("/api/workspace/research-runs","researchRuns");return <><Header title="Research runs" copy="Track provider jobs, review their status, and reopen completed evidence." count={items.length}/>{items.length?<div className={styles.grid}>{items.map(run=><Link className={styles.card} href={`/research-runs/${run.id}`} key={run.id}><div><h2>{run.target||"Research run"}</h2><p>{run.provider||"Research provider"}</p><div className={styles.meta}><span>{run.status}</span>{run.sourceCount!==undefined&&<span>{run.sourceCount} sources</span>}{run.createdAt&&<span>{new Date(run.createdAt).toLocaleString()}</span>}</div></div><Compass size={20}/></Link>)}</div>:<State loading={loading} error={error} icon="runs" empty="Start research from a voice or text conversation. Active runs will remain visible here, even after a reload."/>}</>}
export function SourcesPage(){const {items,loading,error}=useCollection<SourceSummary>("/api/workspace/sources","sources");return <><Header title="Sources" copy="A durable evidence library collected by your approved research runs." count={items.length}/>{items.length?<div className={styles.grid}>{items.map(source=><article className={styles.card} key={source.id}><div><h2><a className={styles.link} href={source.sourceUrl} target="_blank" rel="noreferrer">{source.title||source.sourceUrl}</a></h2><p>{source.channel||new URL(source.sourceUrl).hostname}</p><div className={styles.meta}>{source.provider&&<span>{source.provider}</span>}{typeof source.views==="number"&&<span>{source.views.toLocaleString()} views</span>}</div></div><Database size={20}/></article>)}</div>:<State loading={loading} error={error} icon="sources" empty="Sources appear only after an approved research run completes and its evidence has been normalized."/>}</>}
export function IdeasPage(){const {identity,items,setItems,loading,error}=useCollection<OpportunitySummary>("/api/workspace/opportunities","opportunities");const [filter,setFilter]=useState<"all"|"saved">("all");const update=async(item:OpportunitySummary,state:"saved"|"dismissed")=>{if(!identity.context)return;const prior=items;setItems(current=>current.map(value=>value.id===item.id?{...value,state}:value));try{await workspaceRequest(identity.context.accessToken,"/api/workspace/opportunities",{method:"PATCH",body:JSON.stringify({opportunityId:item.id,state})});}catch{setItems(prior);}};const shown=items.filter(item=>filter==="all"||item.state==="saved");return <><Header title="Saved ideas" copy="Evidence-backed opportunities you can shortlist, review, or dismiss." count={shown.length}/><div className={styles.toolbar}><button aria-pressed={filter==="all"} onClick={()=>setFilter("all")}>All opportunities</button><button aria-pressed={filter==="saved"} onClick={()=>setFilter("saved")}>Saved</button></div><div style={{height:14}}/>{shown.length?<div className={styles.grid}>{shown.map(item=><article className={styles.card} key={item.id}><div><h2>{item.title}</h2><p>{item.rationale}</p><div className={styles.meta}><button onClick={()=>void update(item,"saved")} aria-pressed={item.state==="saved"}>{item.state==="saved"?"Saved":"Save idea"}</button><button onClick={()=>void update(item,"dismissed")}>Dismiss</button><span>{item.sources?.length??0} supporting sources</span></div></div><div className={styles.score}><strong>{item.score}</strong><small>SCORE</small></div></article>)}</div>:<State loading={loading} error={error} icon="ideas" empty={filter==="saved"?"Save an evidence-backed opportunity and it will appear here.":"Ideas are generated only from completed, stored research evidence."}/>}</>}
function Header({title,copy,count}:{title:string;copy:string;count:number}){return <header className={styles.header}><div><h1>{title}</h1><p>{copy}</p></div><span className={styles.badge}>{count} records</span></header>}

