"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { CircleStop, Compass, Database, Headphones, Lightbulb, MessageSquare, Mic, MicOff, Plus, Send, Sparkles, Wifi, WifiOff } from "lucide-react";
import { useRealtimeVoice } from "../hooks/use-realtime-voice";
import { useWorkspaceIdentity } from "@/features/workspace/hooks/use-workspace-identity";
import { WorkspaceAccess } from "@/features/workspace/components/workspace-access";
import styles from "./realtime-voice-workspace.module.css";

const nav = [[MessageSquare,"Conversation"],[Compass,"Research runs"],[Lightbulb,"Saved ideas"],[Database,"Sources"]] as const;
const labels = { idle:"Voice disconnected", "requesting-permission":"Waiting for microphone", connecting:"Connecting securely", connected:"Agent ready", reconnecting:"Reconnecting", error:"Connection needs attention" } as const;

export function RealtimeVoiceWorkspace({conversationId}:{conversationId?:string}={}) {
  const identity = useWorkspaceIdentity();
  const context=identity.context&&conversationId?{...identity.context,conversationId}:identity.context;
  const voice = useRealtimeVoice(context);
  const [text,setText] = useState("");
  const router=useRouter();const pathname=usePathname();const [creating,setCreating]=useState(false);
  const list = useRef<HTMLDivElement>(null);
  useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight,behavior:"smooth"});},[voice.messages,voice.liveTranscript]);
  useEffect(()=>{
    const down=(event:KeyboardEvent)=>{const typing=(event.target as HTMLElement|null)?.matches("textarea,input,[contenteditable=true]");if(event.code==="Space"&&!typing&&!event.repeat){event.preventDefault();void voice.startTalking();}if(event.key==="Escape"&&voice.isAgentSpeaking)voice.interrupt();};
    const up=(event:KeyboardEvent)=>{const typing=(event.target as HTMLElement|null)?.matches("textarea,input,[contenteditable=true]");if(event.code==="Space"&&!typing){event.preventDefault();voice.stopTalking();}};
    window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);};
  },[voice]);
  const submit=()=>{void voice.sendText(text).then(sent=>{if(sent)setText("");});};
  const createConversation=async()=>{if(!context)return;setCreating(true);try{const response=await fetch("/api/workspace/conversations",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${context.accessToken}`},body:JSON.stringify({projectId:context.projectId,title:"New research conversation"})});const payload=await response.json() as {conversation?:{id?:string}};if(response.ok&&payload.conversation?.id)router.push(`/conversations/${payload.conversation.id}`);}finally{setCreating(false);}};
  return <main className={styles.shell}><WorkspaceAccess identity={identity}/><div className={styles.workspace}>
    <aside className={styles.sidebar}><div className={styles.brand}><span><Sparkles size={15}/></span>YT Growth Stack</div><button className={styles.newResearch} onClick={()=>void createConversation()} disabled={creating}><Plus size={14}/>{creating?"Creating...":"New research"}</button><nav aria-label="Primary navigation">{nav.map(([Icon,label])=>{const href=label==="Conversation"?"/":label==="Research runs"?"/research-runs":label==="Saved ideas"?"/ideas":"/sources";const active=href==="/"?(pathname==="/"||pathname.startsWith("/conversations/")):pathname.startsWith(href);return <Link className={active?styles.active:""} aria-current={active?"page":undefined} href={href} key={label}><Icon size={16}/>{label}</Link>})}</nav><div className={styles.sidebarFoot}><strong>Voice first</strong><small>Talk naturally. Every recommendation stays connected to its evidence.</small></div></aside>
    <section className={styles.conversation} aria-label="Growth Agent conversation"><header><div><strong>{voice.conversationTitle??"New research conversation"}</strong><small>Voice-first workspace</small></div><span className={voice.connectionState==="error"?styles.danger:""} role="status">{voice.connectionState==="connected"?<Wifi size={15}/>:<WifiOff size={15}/>}{labels[voice.connectionState]}</span></header>
      <div className={styles.messages} ref={list} aria-live="polite"><div className={styles.transcriptHeader}><strong>Conversation transcript</strong><small>{voice.messages.length ? `${voice.messages.length} messages` : "Voice and text appear here"}</small></div><div className={styles.intro}><strong><Sparkles size={15}/>Growth Agent</strong><p>Tell me what niche, competitors, or audience you want to investigate. I&apos;ll collect evidence, explain what I find, and keep every recommendation traceable.</p></div>{voice.messages.map(message=><article className={message.role==="user"?styles.user:styles.agent} key={message.id}>{message.text}{message.status==="streaming"&&<i aria-hidden="true"/>}</article>)}{voice.liveTranscript&&<div className={styles.transcript}><Mic size={16}/><div><small>Live transcript</small><p>{voice.liveTranscript}</p></div></div>}{voice.error&&<div className={styles.error} role="alert"><MicOff size={18}/><div><strong>Voice is unavailable</strong><p>{voice.error}</p>{voice.permission==="denied"&&<small>Allow microphone access in browser settings, then try again.</small>}</div></div>}</div>
      <footer>{voice.pendingApproval&&<div className={styles.approval} role="alert"><div><strong>Approval required</strong><p>{voice.pendingApproval.summary}</p><small>The agent will not continue until you decide.</small></div><button onClick={voice.rejectTool}>Decline</button><button className={styles.approve} onClick={voice.approveTool}>Approve</button></div>}{voice.toolStatus&&<div className={styles.toolStatus}>{voice.toolStatus}</div>}{voice.isAgentSpeaking&&<button className={styles.interrupt} onClick={voice.interrupt}><CircleStop size={15}/>Interrupt agent <kbd>Esc</kbd></button>}<div className={styles.composer}><button className={`${styles.mic} ${voice.isTalking?styles.talking:""}`} onPointerDown={event=>{event.currentTarget.setPointerCapture(event.pointerId);void voice.startTalking();}} onPointerUp={voice.stopTalking} onPointerCancel={voice.stopTalking} onKeyDown={event=>{if((event.key===" "||event.key==="Enter")&&!event.repeat){event.preventDefault();void voice.startTalking();}}} onKeyUp={event=>{if(event.key===" "||event.key==="Enter"){event.preventDefault();voice.stopTalking();}}} aria-label={voice.connectionState==="connected"?"Hold to talk":"Connect microphone"} aria-pressed={voice.isTalking}><Mic size={21}/></button><textarea value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();submit();}}} placeholder={voice.isTalking?"Listening...":"Ask the agent anything..."} aria-label="Message" rows={1}/><button className={styles.send} onClick={submit} disabled={voice.connectionState==="connected"&&!text.trim()} aria-label={voice.connectionState==="connected"?"Send message":"Connect voice session"}>{voice.connectionState==="connected"?<Send size={17}/>:<Headphones size={17}/>}</button></div><small>{voice.isTalking?"Release to send":voice.connectionState==="connected"?"Hold microphone or Space to talk - Enter sends text":"Connect to start - Permanent API keys stay server-side"}</small></footer>
    </section>
    <aside className={styles.evidence}>
      <header><div><strong>Research desk</strong><small>Sources, patterns, and ideas from your stored research.</small></div><span>{voice.researchResult ? "Live evidence" : voice.researchResultLoading ? "Loading evidence" : "No evidence yet"}</span></header>
      {voice.researchResultError&&<div className={styles.error} role="alert"><Database size={18}/><div><strong>Evidence could not be loaded</strong><p>{voice.researchResultError}</p></div></div>}
      {voice.researchResult&&<section className={styles.liveSummary}><div><strong>{voice.researchResult.sourceCount}</strong><small>normalized sources</small></div><div><strong>{voice.researchResult.analysis.measuredVideos}</strong><small>videos with metrics</small></div><div><strong>{voice.researchResult.opportunities.length}</strong><small>measured opportunities</small></div><article><b>Research assessment</b><p>{voice.researchResult.analysis.conclusion}</p>{voice.researchResult.analysis.medianViews!==null&&<em>Median: {Math.round(voice.researchResult.analysis.medianViews).toLocaleString()} views</em>}</article></section>}
      {!voice.researchResult&&!voice.researchResultError&&<section className={styles.signals}><small>{voice.researchResultLoading?"SYNCING WORKSPACE":"READY FOR RESEARCH"}</small><h3>{voice.researchResultLoading?"Loading stored evidence":"Run research to populate this desk"}</h3><p>{voice.researchResultLoading?"Checking Supabase for completed sources and opportunities.":"Approve a research run and its normalized evidence will appear here automatically."}</p></section>}
      <section className={styles.outliers}><h3>{voice.researchResult?"Collected evidence":"Sources"}</h3><p>{voice.researchResult?"Live, normalized source records from your completed research runs.":"No stored source records are available yet."}</p>{voice.researchResult&&<div>{voice.researchResult.sources.map(source=><article key={source.sourceUrl}><span><a href={source.sourceUrl} target="_blank" rel="noreferrer">{source.title??source.sourceUrl}</a><small>{source.channel??new URL(source.sourceUrl).hostname}</small></span><b>{source.views===null?"No view metric":`${source.views.toLocaleString()} views`}</b></article>)}</div>}</section>
      <section className={styles.ideaPreview}><header><Lightbulb size={18}/><div><strong>Ideas worth testing</strong><p>Generated from retrieved evidence—not generic prompts.</p></div><Link href="/ideas">View all</Link></header>{voice.researchResult?.opportunities.length?<div className={styles.ideaList}>{voice.researchResult.opportunities.map(opportunity=><article key={opportunity.id}><div><strong>{opportunity.title}</strong><p>{opportunity.rationale}</p></div><em>{opportunity.score}/100</em></article>)}</div>:<p className={styles.ideaEmpty}>{voice.researchResult?"No measured opportunity crossed the current evidence threshold.":"Measured opportunities will appear here after research completes."}</p>}</section>
    </aside>
  </div></main>;
}
