"use client";
import { useState } from "react";
import { BookOpen, Compass, Database, Lightbulb, MessageSquare, Mic, Plus, Sparkles } from "lucide-react";

const nav = [[MessageSquare,"Conversation"],[Compass,"Research runs"],[Lightbulb,"Saved ideas"],[Database,"Sources"]] as const;

export function VoiceWorkspace() {
  const [listening,setListening]=useState(false);
  const [message,setMessage]=useState("");
  return <main className="app-shell"><div className="workspace">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>YT Growth Stack</div><button className="new-thread"><Plus size={14}/>New research</button><nav className="nav-section" aria-label="Primary navigation"><p className="nav-label">Workspace</p>{nav.map(([Icon,label],index)=><span className={`nav-item ${index===0?"active":""}`} key={label}><Icon size={16}/>{label}</span>)}</nav><div className="sidebar-foot"><strong>Voice first</strong><span>Talk naturally. Every recommendation stays connected to its evidence.</span></div></aside>
    <section className="conversation"><header className="conversation-header"><div className="conversation-title"><strong>AI productivity channels</strong><span>Competitor research workspace</span></div><div className="live-state"><span className="live-dot"/>Agent ready</div></header><div className="message-list" aria-live="polite"><div className="agent-intro"><div className="agent-label"><Sparkles size={15}/>Growth Agent</div><p className="agent-copy">Tell me what niche, competitors, or audience you want to investigate. I’ll collect the evidence, explain what I find, and keep every recommendation traceable.</p></div><div className="user-message">Find underserved video ideas from these five competitors. Focus on topics gaining momentum this month.</div><div className="run-card"><div className="run-top"><strong>Competitor opportunity scan</strong><span className="run-status">Researching</span></div><div className="pipeline"><span className="pipeline-step done">✓ Apify · 214 videos</span><span className="pipeline-step active">Firecrawl · 12 pages</span><span className="pipeline-step">Analysis · queued</span></div></div><div className="opportunity"><small>Early opportunity</small><span>Local AI agents for non-engineers</span><small>Supported by 12 competitor videos and 8 external sources</small></div></div><div className="composer-wrap"><div className="composer"><button className={`mic-button ${listening?"listening":""}`} onClick={()=>setListening(v=>!v)} aria-label={listening?"Stop listening":"Start speaking"}><Mic size={20}/></button><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={listening?"Listening…":"Ask the agent or hold the microphone to talk…"} aria-label="Message"/><button className="send-button" disabled={!message.trim()}>Send</button></div><p className="composer-note">Demo interaction. Live audio activates after OpenAI credentials are configured.</p></div></section>
    <aside className="evidence-panel"><div className="panel-heading"><strong>Evidence</strong><span>Live run</span></div><div className="metric-grid"><div className="metric"><strong>214</strong><span>Videos collected</span></div><div className="metric"><strong>12</strong><span>Web sources</span></div></div><div className="source-list"><h3>Recent sources</h3><div className="source"><strong>YouTube competitor dataset</strong><span>Apify · 2 minutes ago</span></div><div className="source"><strong>AI workflow trend report</strong><span>Firecrawl · collecting</span></div><div className="source"><strong>Creator newsletters</strong><span>Firecrawl · queued</span></div></div><div className="theme-note"><BookOpen size={15}/><br/>Theme tokens are isolated in <code>globals.css</code>. Paste your tweakcn theme and this surface can adopt it without changing product logic.</div></aside>
  </div></main>;
}
