"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { ConnectionState, ConversationMessage, MicrophonePermission, PendingToolApproval, RealtimeEvent, RealtimeSessionResponse, RealtimeWorkspaceContext } from "../types/realtime";

const DEFAULT_MODEL="gpt-realtime-2.1";
const approvalTools=new Set(["create_research","cancel_research"]);
const toolLabels:Record<string,string>={create_research:"Start a paid scraper research run",cancel_research:"Cancel the current research run",search_youtube:"Search official YouTube metadata",get_research_status:"Check research status",collect_research_evidence:"Collect completed evidence"};
function sessionCredential(payload:RealtimeSessionResponse){if(typeof payload.client_secret==="string")return payload.client_secret;return payload.client_secret?.value??payload.value??payload.ephemeral_key}
function messageId(prefix:string){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2)}`}
type ResearchSourceView={title:string|null;sourceUrl:string;views:number|null;channel:string|null};
type ResearchResultView={status:string;sourceCount:number;sources:ResearchSourceView[];opportunities:Array<{id:string;title:string;rationale:string;score:number}>};
function researchResultView(payload:unknown):ResearchResultView|null{if(!payload||typeof payload!=="object")return null;const result=(payload as {result?:unknown}).result;if(!result||typeof result!=="object")return null;const record=result as {status?:unknown;evidence?:unknown;opportunities?:unknown};const opportunities=Array.isArray(record.opportunities)?record.opportunities.flatMap(value=>{if(!value||typeof value!=="object")return[];const item=value as Record<string,unknown>;return typeof item.id==="string"&&typeof item.title==="string"&&typeof item.rationale==="string"&&typeof item.score==="number"?[{id:item.id,title:item.title,rationale:item.rationale,score:item.score}]:[]}):[];const sources=Array.isArray(record.evidence)?record.evidence.flatMap(value=>{if(!value||typeof value!=="object")return[];const item=value as Record<string,unknown>;const metrics=item.metrics&&typeof item.metrics==="object"?item.metrics as Record<string,unknown>:{};if(typeof item.sourceUrl!=="string")return[];return[{title:typeof item.title==="string"?item.title:null,sourceUrl:item.sourceUrl,views:typeof metrics.views==="number"?metrics.views:null,channel:typeof metrics.channel==="string"?metrics.channel:null}]}):[];return{status:typeof record.status==="string"?record.status:"completed",sourceCount:sources.length,sources,opportunities}}

export function useRealtimeVoice(workspace:RealtimeWorkspaceContext|null=null){
  const [connectionState,setConnectionState]=useState<ConnectionState>("idle");const [researchResult,setResearchResult]=useState<ResearchResultView|null>(null);const [permission,setPermission]=useState<MicrophonePermission>("prompt");const [isTalking,setIsTalking]=useState(false);const [isAgentSpeaking,setIsAgentSpeaking]=useState(false);const [liveTranscript,setLiveTranscript]=useState("");const [messages,setMessages]=useState<ConversationMessage[]>([]);const [error,setError]=useState<string|null>(null);const [pendingApproval,setPendingApproval]=useState<PendingToolApproval|null>(null);const [toolStatus,setToolStatus]=useState<string|null>(null);
  const peerRef=useRef<RTCPeerConnection|null>(null);const channelRef=useRef<RTCDataChannel|null>(null);const streamRef=useRef<MediaStream|null>(null);const audioRef=useRef<HTMLAudioElement|null>(null);const assistantDraftRef=useRef("");const speechDetectedRef=useRef(false);
  const persistMessage=useCallback(async(role:"user"|"assistant",content:string)=>{if(!workspace||!content.trim())return;try{await fetch("/api/workspace/messages",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${workspace.accessToken}`},body:JSON.stringify({conversationId:workspace.conversationId,kind:role,content:content.trim(),clientId:crypto.randomUUID()})});}catch{/* Keep the live session usable if persistence is temporarily unavailable. */}},[workspace]);
  const sendEvent=useCallback((event:Record<string,unknown>)=>{const channel=channelRef.current;if(channel?.readyState==="open")channel.send(JSON.stringify(event));},[]);
  const returnToolOutput=useCallback((callId:string,output:unknown)=>{sendEvent({type:"conversation.item.create",item:{type:"function_call_output",call_id:callId,output:JSON.stringify(output)}});sendEvent({type:"response.create"});},[sendEvent]);
  const executeTool=useCallback(async(call:{callId:string;name:string;arguments:unknown})=>{
    if(!workspace){returnToolOutput(call.callId,{error:"Authenticate and create a workspace before running tools."});return;}
    const invoke=async(name:string,args:unknown)=>{const response=await fetch("/api/tools/execute",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${workspace.accessToken}`},body:JSON.stringify({name,arguments:args,projectId:workspace.projectId,conversationId:workspace.conversationId})});const payload:unknown=await response.json();if(!response.ok)throw new Error("The research tool could not complete.");return payload;};
    setToolStatus(`Running ${toolLabels[call.name]??call.name}...`);
    try{
      const payload=await invoke(call.name,call.arguments);const collected=researchResultView(payload);if(collected&&call.name!=="create_research")setResearchResult(collected);returnToolOutput(call.callId,payload);setToolStatus(`${toolLabels[call.name]??call.name} completed`);
      const result=payload&&typeof payload==="object"?(payload as {result?:unknown}).result:null;const record=result&&typeof result==="object"?result as Record<string,unknown>:null;
      if(call.name==="create_research"&&record&&typeof record.id==="string")void(async()=>{
        const researchId=record.id;
        for(let attempt=0;attempt<120;attempt+=1){
          await new Promise(resolve=>setTimeout(resolve,3000));
          const statusPayload=await invoke("get_research_status",{researchId});const statusResult=(statusPayload as {result?:unknown}).result;const statusRecord=statusResult&&typeof statusResult==="object"?statusResult as Record<string,unknown>:null;const status=typeof statusRecord?.status==="string"?statusRecord.status:"unknown";
          setToolStatus(`Research ${status}...`);
          if(status==="queued"||status==="running")continue;
          if(status==="succeeded"){
            setToolStatus("Collecting and analyzing evidence...");const collectedPayload=await invoke("collect_research_evidence",{researchId});const view=researchResultView(collectedPayload);if(view){setResearchResult(view);const update={researchId,status:view.status,sources:view.sources,opportunities:view.opportunities};sendEvent({type:"conversation.item.create",item:{type:"message",role:"user",content:[{type:"input_text",text:`Automated research update. Use only this stored evidence and cite its source URLs: ${JSON.stringify(update)}`}]}});sendEvent({type:"response.create"});setToolStatus(`Research complete: ${view.sourceCount} sources analyzed`);}return;
          }
          setToolStatus(`Research ${status}`);return;
        }
        setToolStatus("Research is still running. Ask me to check it again.");
      })().catch(cause=>setToolStatus(cause instanceof Error?cause.message:"Research monitoring failed."));
    }catch(cause){const message=cause instanceof Error?cause.message:"The research tool failed.";returnToolOutput(call.callId,{error:message});setToolStatus(message);}
  },[workspace,returnToolOutput,sendEvent]);
  const handleEvent=useCallback((event:RealtimeEvent)=>{switch(event.type){
    case "input_audio_buffer.speech_started":speechDetectedRef.current=true;setLiveTranscript("");break;
    case "conversation.item.input_audio_transcription.delta":setLiveTranscript(current=>current+(event.delta??""));break;
    case "conversation.item.input_audio_transcription.completed":{const transcript=event.transcript?.trim();if(transcript){const id=event.item_id??messageId("user");setMessages(current=>[...current,{id,role:"user",text:transcript,status:"complete"}]);void persistMessage("user",transcript);}setLiveTranscript("");break;}
    case "response.audio.delta":case "response.output_audio.delta":setIsAgentSpeaking(true);break;
    case "response.audio_transcript.delta":case "response.output_audio_transcript.delta":case "response.output_text.delta":{const delta=event.delta??"";assistantDraftRef.current+=delta;const id=event.response_id??"assistant-stream";setMessages(current=>[...current.filter(message=>message.id!=="assistant-stream"&&message.id!==id),{id,role:"assistant",text:assistantDraftRef.current,status:"streaming"}]);break;}
    case "response.function_call_arguments.done":{if(!event.call_id||!event.name)return;let args:unknown={};try{args=JSON.parse(event.arguments??"{}");}catch{returnToolOutput(event.call_id,{error:"The tool arguments were invalid JSON."});return;}const call={callId:event.call_id,name:event.name,arguments:args};if(approvalTools.has(event.name)){const values=args&&typeof args==="object"?args as Record<string,unknown>:{};const cap=values.provider==="apify"?` capped at ${typeof values.maxVideos==="number"?values.maxVideos:10} videos`:"";const targets=Array.isArray(values.channels)?` for ${values.channels.join(", ")}`:"";setPendingApproval({...call,summary:`${toolLabels[event.name]??event.name}${cap}${targets}`});setToolStatus("Waiting for your approval");}else void executeTool(call);break;}
    case "response.done":{setIsAgentSpeaking(false);const completed=assistantDraftRef.current.trim();setMessages(current=>current.map(message=>message.status==="streaming"?{...message,status:"complete"}:message));if(completed)void persistMessage("assistant",completed);assistantDraftRef.current="";break;}
    case "error":setError(event.error?.message??"The voice session reported an error.");break;
  }},[executeTool,persistMessage,returnToolOutput]);
  const disconnect=useCallback(()=>{channelRef.current?.close();peerRef.current?.close();streamRef.current?.getTracks().forEach(track=>track.stop());audioRef.current?.pause();channelRef.current=null;peerRef.current=null;streamRef.current=null;audioRef.current=null;setIsTalking(false);setIsAgentSpeaking(false);setPendingApproval(null);setConnectionState("idle");},[]);
  const connect=useCallback(async()=>{if(!workspace){setConnectionState("error");setError("Sign in and create a workspace before starting voice.");return;}if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection==="undefined"){setPermission("unsupported");setError("This browser does not support microphone-based Realtime conversations.");return;}if((connectionState==="connected"&&streamRef.current)||connectionState==="connecting")return;channelRef.current?.close();peerRef.current?.close();setError(null);setConnectionState("requesting-permission");try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});stream.getAudioTracks().forEach(track=>{track.enabled=false});streamRef.current=stream;setPermission("granted");setConnectionState("connecting");const sessionResponse=await fetch("/api/realtime/session",{method:"POST",headers:{authorization:`Bearer ${workspace.accessToken}`}});const payload=await sessionResponse.json() as RealtimeSessionResponse&{error?:string};if(!sessionResponse.ok)throw new Error(payload.error??"Could not create a voice session.");const credential=sessionCredential(payload);if(!credential)throw new Error("The voice session did not return a temporary credential.");const peer=new RTCPeerConnection();peerRef.current=peer;stream.getTracks().forEach(track=>peer.addTrack(track,stream));const audio=new Audio();audio.autoplay=true;audioRef.current=audio;peer.ontrack=({streams})=>{audio.srcObject=streams[0]};peer.onconnectionstatechange=()=>{if(peer.connectionState==="connected")setConnectionState("connected");if(peer.connectionState==="disconnected")setConnectionState("reconnecting");if(peer.connectionState==="failed"){setConnectionState("error");setError("The voice connection failed. Disconnect and try again.");}};const channel=peer.createDataChannel("oai-events");channelRef.current=channel;channel.onmessage=({data})=>{try{handleEvent(JSON.parse(data) as RealtimeEvent)}catch{}};const offer=await peer.createOffer();await peer.setLocalDescription(offer);const model=payload.model??payload.session?.model??DEFAULT_MODEL;const sdpResponse=await fetch(`https://api.openai.com/v1/realtime/calls?model=${encodeURIComponent(model)}`,{method:"POST",body:offer.sdp,headers:{Authorization:`Bearer ${credential}`,"Content-Type":"application/sdp"}});if(!sdpResponse.ok)throw new Error("OpenAI could not establish the voice connection.");await peer.setRemoteDescription({type:"answer",sdp:await sdpResponse.text()});}catch(cause){streamRef.current?.getTracks().forEach(track=>track.stop());const denied=cause instanceof DOMException&&(cause.name==="NotAllowedError"||cause.name==="SecurityError");if(denied)setPermission("denied");setConnectionState("error");setError(cause instanceof Error?cause.message:"Could not start the voice session.");}},[connectionState,handleEvent,workspace]);
  const connectText=useCallback(async()=>{if(!workspace){setConnectionState("error");setError("Sign in and create a workspace before starting chat.");return false;}if(typeof RTCPeerConnection==="undefined"){setConnectionState("error");setError("This browser does not support Realtime chat.");return false;}if(channelRef.current?.readyState==="open")return true;setError(null);setConnectionState("connecting");try{const sessionResponse=await fetch("/api/realtime/session",{method:"POST",headers:{authorization:`Bearer ${workspace.accessToken}`}});const payload=await sessionResponse.json() as RealtimeSessionResponse&{error?:string};if(!sessionResponse.ok)throw new Error(payload.error??"Could not create a chat session.");const credential=sessionCredential(payload);if(!credential)throw new Error("The chat session did not return a temporary credential.");const peer=new RTCPeerConnection();peerRef.current=peer;peer.addTransceiver("audio",{direction:"recvonly"});const audio=new Audio();audio.autoplay=true;audioRef.current=audio;peer.ontrack=({streams})=>{audio.srcObject=streams[0]};const channel=peer.createDataChannel("oai-events");channelRef.current=channel;channel.onmessage=({data})=>{try{handleEvent(JSON.parse(data) as RealtimeEvent)}catch{}};const opened=new Promise<boolean>(resolve=>{const timeout=window.setTimeout(()=>resolve(false),10000);channel.onopen=()=>{window.clearTimeout(timeout);setConnectionState("connected");resolve(true);};});const offer=await peer.createOffer();await peer.setLocalDescription(offer);const model=payload.model??payload.session?.model??DEFAULT_MODEL;const sdpResponse=await fetch(`https://api.openai.com/v1/realtime/calls?model=${encodeURIComponent(model)}`,{method:"POST",body:offer.sdp,headers:{Authorization:`Bearer ${credential}`,"Content-Type":"application/sdp"}});if(!sdpResponse.ok)throw new Error("OpenAI could not establish the chat connection.");await peer.setRemoteDescription({type:"answer",sdp:await sdpResponse.text()});if(!await opened)throw new Error("The chat connection timed out.");return true;}catch(cause){setConnectionState("error");setError(cause instanceof Error?cause.message:"Could not start the chat session.");return false;}},[handleEvent,workspace]);
  const startTalking=useCallback(async()=>{if(connectionState!=="connected"){await connect();return;}if(isAgentSpeaking)sendEvent({type:"response.cancel"});speechDetectedRef.current=false;streamRef.current?.getAudioTracks().forEach(track=>{track.enabled=true});setLiveTranscript("");setIsTalking(true);},[connect,connectionState,isAgentSpeaking,sendEvent]);
  const stopTalking=useCallback(()=>{streamRef.current?.getAudioTracks().forEach(track=>{track.enabled=false});if(isTalking&&!speechDetectedRef.current)sendEvent({type:"input_audio_buffer.clear"});setIsTalking(false);},[isTalking,sendEvent]);
  const interrupt=useCallback(()=>{sendEvent({type:"response.cancel"});audioRef.current?.pause();setIsAgentSpeaking(false);},[sendEvent]);
  const sendText=useCallback(async(text:string)=>{const clean=text.trim();if(!clean)return false;if(channelRef.current?.readyState!=="open"&&!await connectText())return false;const id=messageId("user");setMessages(current=>[...current,{id,role:"user",text:clean,status:"complete"}]);void persistMessage("user",clean);sendEvent({type:"conversation.item.create",item:{type:"message",role:"user",content:[{type:"input_text",text:clean}]}});sendEvent({type:"response.create"});return true;},[connectText,persistMessage,sendEvent]);
  const approveTool=useCallback(()=>{if(!pendingApproval)return;const call=pendingApproval;const values=call.arguments&&typeof call.arguments==="object"?call.arguments as Record<string,unknown>:{};setPendingApproval(null);void executeTool({...call,arguments:{...values,confirmed:true}});},[pendingApproval,executeTool]);
  const rejectTool=useCallback(()=>{if(!pendingApproval)return;returnToolOutput(pendingApproval.callId,{error:"The user did not approve this action."});setPendingApproval(null);setToolStatus("Action declined");},[pendingApproval,returnToolOutput]);
  useEffect(()=>disconnect,[disconnect]);
  useEffect(()=>{if(!workspace)return;let cancelled=false;void fetch(`/api/workspace/conversations/${workspace.conversationId}`,{headers:{authorization:`Bearer ${workspace.accessToken}`}}).then(async response=>response.ok?response.json():null).then((payload:unknown)=>{if(cancelled||!payload||typeof payload!=="object")return;const values=(payload as {messages?:unknown}).messages;if(!Array.isArray(values))return;setMessages(values.flatMap((value,index)=>{if(!value||typeof value!=="object")return[];const item=value as Record<string,unknown>;const role=item.kind??item.role;const message=item.content??item.text;if((role!=="user"&&role!=="assistant")||typeof message!=="string")return[];return[{id:typeof item.id==="string"?item.id:`stored-${index}`,role,text:message,status:"complete" as const}];}));}).catch(()=>{});return()=>{cancelled=true};},[workspace]);
  return{connectionState,permission,isTalking,isAgentSpeaking,liveTranscript,messages,error,pendingApproval,toolStatus,researchResult,connect,disconnect,startTalking,stopTalking,interrupt,sendText,approveTool,rejectTool};
}