-- YT Growth Stack initial schema
create extension if not exists pgcrypto;

create type public.research_run_status as enum ('queued','running','succeeded','failed','cancelled');
create type public.message_kind as enum ('user_text','user_transcript','assistant_text','assistant_audio','tool_started','tool_completed','tool_failed','research_progress','evidence','opportunity','approval_request');

create table public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, niche text, created_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, title text not null default 'New research', created_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, kind public.message_kind not null, content jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.competitors (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, platform text not null, external_url text not null, display_name text, created_at timestamptz not null default now(), unique(project_id,external_url));
create table public.research_runs (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, conversation_id uuid references public.conversations(id) on delete set null, status public.research_run_status not null default 'queued', budget_cents integer not null default 0 check (budget_cents>=0), started_at timestamptz, finished_at timestamptz, error jsonb, created_at timestamptz not null default now());
create table public.source_documents (id uuid primary key default gen_random_uuid(), research_run_id uuid not null references public.research_runs(id) on delete cascade, provider text not null check(provider in ('apify','firecrawl','manual')), source_url text not null, title text, raw_payload jsonb not null, content_text text, captured_at timestamptz not null default now(), unique(research_run_id,source_url));
create table public.opportunities (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, research_run_id uuid not null references public.research_runs(id) on delete cascade, title text not null, rationale text not null, score numeric(5,2), evidence_ids uuid[] not null default '{}', created_at timestamptz not null default now());

alter table public.projects enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.competitors enable row level security; alter table public.research_runs enable row level security; alter table public.source_documents enable row level security; alter table public.opportunities enable row level security;
create policy "owners manage projects" on public.projects for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "owners manage conversations" on public.conversations for all using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid()));
create policy "owners manage messages" on public.messages for all using(exists(select 1 from public.conversations c join public.projects p on p.id=c.project_id where c.id=conversation_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.conversations c join public.projects p on p.id=c.project_id where c.id=conversation_id and p.owner_id=auth.uid()));
create policy "owners manage competitors" on public.competitors for all using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid()));
create policy "owners manage runs" on public.research_runs for all using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid()));
create policy "owners manage sources" on public.source_documents for all using(exists(select 1 from public.research_runs r join public.projects p on p.id=r.project_id where r.id=research_run_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.research_runs r join public.projects p on p.id=r.project_id where r.id=research_run_id and p.owner_id=auth.uid()));
create policy "owners manage opportunities" on public.opportunities for all using(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid())) with check(exists(select 1 from public.projects p where p.id=project_id and p.owner_id=auth.uid()));
